name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

jobs:

  build_and_deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia.gcr.io/${{ secrets.GCP_PROJECT_ID}}/bot-worker
    steps:
      - uses: actions/checkout@v2
      
      - name: Authenticate GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
        
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      
      - name: Push to GCR
        run: docker push $IMAGE_NAME

      - name: deploy to cloud run
        run: |
          gcloud run deploy bot-worker \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --image $IMAGE_NAME \
          --region asia-southeast2 \
          --platform managed
